apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    mainfests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: samyek/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    -  image: samyek/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .